beginend: ensure num-prefixed motions do not break when enabled
emacs-evil/evil-collection pull request #534
Opened 2021-09-14 02:10 UTC by balajisivaraman

As discussed in #533, this PR provides a fix to ensure number-prefixed `gg` and `G` motions do not break when `beginend` support is enabled.

2021-09-14 04:12 UTC, condy0919 requested changes

2021-09-14 04:12 UTC, condy0919 commented on modes/beginend/evil-collection-beginend.el
> +    `(progn
`progn` is redundant in `let`

2021-09-14 04:12 UTC, condy0919 commented on modes/beginend/evil-collection-beginend.el
> +    `(progn
Same with the above one

2021-09-14 04:12 UTC, condy0919 commented on modes/beginend/evil-collection-beginend.el
> +    (progn
Same with the above one

2021-09-14 16:14 UTC, balajisivaraman commented
@condy0919, Within the `defmacro`, if I don't use `progn`, only the last line is getting evaluated. Can you help me with this? Is there another Emacs Lisp form that I can use within the `defmacro`? Or am I missing something?

2021-09-15 16:26 UTC, balajisivaraman commented
@condy0919, Correct me if I'm wrong, but from looking at files like `evil-macros.el` also, if I want the macro to expand into something that runs multiple statements, then they have used `progn`. This can be seen, for example, in [`evil-define-motion`](https://github.com/emacs-evil/evil/blob/master/evil-macros.el#L111).

My knowledge of Emacs Lisp macros is limited beyond that. If there is a mechanism to achieve the same effect in a `defmacro` without using the `progn`, please let me know.

2021-09-15 20:06 UTC, condy0919 commented
Sorry, I forgot it's used in macro for `,` expansion

2021-09-15 20:17 UTC, condy0919 requested changes

2021-09-15 20:17 UTC, condy0919 commented on modes/beginend/evil-collection-beginend.el
> +(defmacro evil-beginend-goto-end-motion (ec-mode-name)
nitpicking: `evil-beginend--define-goto-end-motion` looks more meaningful. Two `-`s since is a private macro.

2021-09-15 20:23 UTC, condy0919 commented on modes/beginend/evil-collection-beginend.el
> +(defconst evil-collection-beginend-modes-alist '("bs-mode"
It's not an `alist`, `alist` is something like:

```elisp
(setq foo '((a . 0)
            (b . 1)
            (c . 2)))

(require 'cl-lib)
(cl-assert (equal (alist-get 'a foo) 0))
(cl-assert (equal (alist-get 'b foo) 1))
(cl-assert (equal (alist-get 'c foo) 2))
```

2021-09-15 20:36 UTC, condy0919 commented on modes/beginend/evil-collection-beginend.el
> +    (eval `(evil-beginend-goto-beginning-motion ,ec-mode-name))
Can we aovid `eval`? it's dangerous

2021-09-16 03:37 UTC, balajisivaraman commented
@condy0919, Done! Without `eval`, I had to resort to the inlining all the macro calls. Otherwise, whether I use `mapc` or `dolist`, the macro gets expanded but never evaluated, I guess causing the bindings to not be set. I feel this is okay. But please let me know if you feel otherwise.

2021-09-16 09:00 UTC, condy0919 commented
CI failed with

```
modes/beginend/evil-collection-beginend.el:149:1:Error: the following functions are not known to be defined: beginend-bs-mode-goto-beginning, beginend-bs-mode-goto-end, beginend-rg-mode-goto-beginning, beginend-rg-mode-goto-end, beginend-org-mode-goto-beginning, beginend-org-mode-goto-end, beginend-deft-mode-goto-beginning, beginend-deft-mode-goto-end, beginend-prog-mode-goto-beginning, beginend-prog-mode-goto-end, beginend-LaTeX-mode-goto-beginning, beginend-LaTeX-mode-goto-end, beginend-nroam-mode-goto-beginning, beginend-nroam-mode-goto-end, beginend-occur-mode-goto-beginning, beginend-occur-mode-goto-end, beginend-vc-dir-mode-goto-beginning, beginend-vc-dir-mode-goto-end, beginend-ibuffer-mode-goto-beginning, beginend-ibuffer-mode-goto-end, beginend-message-mode-goto-beginning, beginend-message-mode-goto-end, beginend-outline-mode-goto-beginning, beginend-outline-mode-goto-end, beginend-prodigy-mode-goto-beginning, beginend-prodigy-mode-goto-end, beginend-org-agenda-mode-goto-beginning, beginend-org-agenda-mode-goto-end, beginend-compilation-mode-goto-beginning, beginend-compilation-mode-goto-end, beginend-epa-key-list-mode-goto-beginning, beginend-epa-key-list-mode-goto-end, beginend-magit-status-mode-goto-beginning, beginend-magit-status-mode-goto-end, beginend-elfeed-search-mode-goto-beginning, beginend-elfeed-search-mode-goto-end, beginend-magit-revision-mode-goto-beginning, beginend-magit-revision-mode-goto-end, beginend-notmuch-search-mode-goto-beginning, beginend-notmuch-search-mode-goto-end, beginend-recentf-dialog-mode-goto-beginning, beginend-recentf-dialog-mode-goto-end
```

2021-09-16 09:07 UTC, balajisivaraman commented
@condy0919, Yeah, my bad. If I use `eval` to evaluate the macro, it works fine. If I don't use `eval` and inline the macro calls, this happened. I'll try to figure it out in the evening and send a final version today evening or tomorrow. Thanks for the understanding and support.

2021-09-16 09:09 UTC, condy0919 commented
Happy hacking :-)

2021-09-16 15:37 UTC, balajisivaraman commented
@condy0919, Thank you for the patience! Hopefully it looks good now. Like I said in my earlier struck out comment, the actual definition is quite long, but this is the only way to achieve it without using `eval`. My solution of using a list of modes and then doing a `mapc` or a `dolist` required another round of evaluation of the expanded macro, which was unsafe.

2021-09-16 16:26 UTC, condy0919 commented
Thanks

2021-09-16 16:26 UTC, merged