Added Smerge Mode Bindings
emacs-evil/evil-collection pull request #556
Opened 2021-12-04 17:01 UTC by pspiagicw

Added Smerge bindings according to #519, does follow spacemacs bindings as declared here(https://github.com/syl20bnr/spacemacs/pull/8505)

Keybindings start with 'g' prefix.Changes are welcome!

2021-12-04 18:05 UTC, condy0919 commented
```
evil-collection-smerge-mode.el:50:4: warning: Closing parens should not be wrapped onto new lines.
```

package-lint complains

2021-12-04 18:41 UTC, pspiagicw commented
Must be fixed now.

2021-12-06 18:06 UTC, condy0919 commented on modes/smerge/evil-collection-smerge-mode.el
> +    "gn" 'smerge-next
`gj` may be more proper.

2021-12-06 18:06 UTC, condy0919 requested changes

2021-12-06 18:06 UTC, condy0919 commented on modes/smerge/evil-collection-smerge-mode.el
> +    "gp" 'smerge-prev
`gk`

2021-12-08 09:45 UTC, pspiagicw commented on modes/smerge/evil-collection-smerge-mode.el
> +    "gn" 'smerge-next
Changes added

2021-12-08 22:18 UTC, condy0919 commented
Thanks

2021-12-08 22:19 UTC, merged