Add support for lms.el
emacs-evil/evil-collection pull request #569
Opened 2021-12-19 12:18 UTC by edgar-vincent

Follow up on #542. Thanks @condy0919 for reviewing it and please excuse me for not having provided feedback earlier.

This version replaces the lambdas bound to `q` with functions as requested. 
Regarding https://github.com/emacs-evil/evil-collection/pull/542#discussion_r725657871, I took these lines from the lms.el package itself. It seems those remappings are indeed necessary because they are used in contexts where the last line is a blank line. The point thus needs to be placed on the penultimate line. Do tell me should I have overlooked a better solution.

Thanks again!

2021-12-19 12:31 UTC, condy0919 commented
```
modes/lms/evil-collection-lms.el:68:62:Error: reference to free variable ‘lms--ui-pl-tracks’
```

2021-12-19 13:08 UTC, condy0919 commented on modes/lms/evil-collection-lms.el
> +    [remap evil-goto-line] '(lambda () (interactive) (goto-char (max-char)) (forward-line -1))
Make it a function.

2021-12-21 09:15 UTC, condy0919 commented
```
modes/lms/evil-collection-lms.el:208:1:Error: the function ‘lms-ui-playing-now-refresh’ is not known to be defined.
```

2021-12-27 17:48 UTC, condy0919 requested changes

2021-12-27 17:48 UTC, condy0919 commented on modes/lms/evil-collection-lms.el
> +    [remap evil-goto-line] 'evil-collection-lms-goto-bottom
Since it remaps `evil-goto-line` to `evil-collection-lms-goto-bottom`, it should take care of the prefix numeric arg.

2021-12-27 17:48 UTC, condy0919 commented on modes/lms/evil-collection-lms.el
> +    [remap evil-goto-line] 'evil-collection-lms-goto-bottom
ditto.

BTW, <kbd>C-M-\\</kbd> on the region for correct indentation.

2021-12-27 17:48 UTC, condy0919 commented on modes/lms/evil-collection-lms.el
> +    [remap evil-goto-line] 'evil-collection-lms-goto-bottom
indentation

2021-12-27 17:48 UTC, condy0919 commented on modes/lms/evil-collection-lms.el
> +    [remap evil-goto-line] 'evil-collection-lms-goto-bottom
indentation.

2021-12-27 17:48 UTC, condy0919 commented on modes/lms/evil-collection-lms.el
> +    "J"              'lms-ui-playing-now-next
I personally prefer <kbd>C-j</kbd> over <kbd>J</kbd>. <kbd>J</kbd> is used to jump, <kbd>K</kbd> is for lookup.

2021-12-27 17:48 UTC, condy0919 commented on modes/lms/evil-collection-lms.el
> +    "K"              'lms-ui-playing-now-prev
See above comment.

2021-12-27 17:48 UTC, condy0919 commented on modes/lms/evil-collection-lms.el
> +    "u"              'lms-ui-playing-now-refresh
`u` -> `gr`

2021-12-27 17:48 UTC, condy0919 commented on modes/lms/evil-collection-lms.el
> +    "K"             'lms-ui-track-info-prev
`K` -> `C-k`, `J` -> `C-j`

2022-04-12 13:51 UTC, jojojames commented
Feel free to reopen after making the changes, thanks!

2022-04-12 13:51 UTC, closed without merging

2023-01-23 19:43 UTC, edgar-vincent commented
@jojojames I've updated the branch. Can you reopen the pull request or should I create a new one?

Thanks a lot!