Add support for Gited.
emacs-evil/evil-collection pull request #689
Opened 2022-11-26 22:32 UTC by okamsn

These bindings are similar to Dired.

### Brief summary of what the package does

Gited is an interface to manage Git branches and tags in a way similar to Dired.

- Not all of the available commands are bound in `gited-mode-map`, so I did 
  not bind all of them for Evil Collection.
- I had to move some commands around to more closely match how Dired is set up.

### Direct link to the package repository

https://git.savannah.gnu.org/cgit/emacs/elpa.git/?h=externals/gited

### Checklist

Assume you're working on `mpc` mode:

- [x] byte-compiles cleanly
- [x] `M-x checkdoc` is happy. Don't manually write `(provide 'evil-collection-mpc)`, `M-x checkdoc` can do it automatically for you
- [x] define `evil-collection-mpc-setup` with `defun`
- [x] define `evil-collection-mpc-mode-maps` with `defconst`
- [x] All functions should start with `evil-collection-mpc-`

2022-11-26 22:44 UTC, okamsn commented
The tests say that Gited is unavailable. This makes sense, since it is a package from ELPA. What is the way to make the tests install the package?

2022-11-27 17:59 UTC, condy0919 requested changes

2022-11-27 17:59 UTC, condy0919 commented on modes/gited/evil-collection-gited.el
> +(require 'gited)
`(require 'gited nil t)`

2022-11-27 17:59 UTC, condy0919 commented on modes/gited/evil-collection-gited.el
> +;; Copyright (C) 2017 James Nguyen
2022, and your name

2022-11-27 17:59 UTC, condy0919 commented on modes/gited/evil-collection-gited.el
> +;; Maintainer: James Nguyen <james@jojojames.com>
your name

2022-11-27 17:59 UTC, condy0919 commented on modes/gited/evil-collection-gited.el
> +    "q" #'quit-window
do `evil-collection-set-readonly-bindings` first, then remove `q`

2022-11-27 17:59 UTC, condy0919 commented on modes/gited/evil-collection-gited.el
> +    "}" #'tabulated-list-widen-current-column
Those two have been set in ` evil-collection-tabulated-list.el` and can be safely removed. do double check later by `describe-keymap tabulated-list-mode-map`

2022-11-28 00:22 UTC, okamsn commented
I have made those changes. It now fails on the snapshot due to the Company setup.

2022-11-28 16:40 UTC, condy0919 commented
btw, change your commit message to `package-name: description ...` format. e.g.,

```
gited: initial support

the long description stays here.
```

2022-11-28 19:40 UTC, okamsn commented
OK, those are done. Is there anything else that you would like changed?

2022-11-29 04:41 UTC, condy0919 commented
LGTM

2022-11-29 04:42 UTC, merged