helm: hide evil cursor in minibuffer
emacs-evil/evil-collection pull request #732
Opened 2023-05-23 13:05 UTC by taquangtrung

### Brief summary of what the package does

Hi, 

This PR enables hiding cursor in minibuffer when a Helm session is active.

I fixed the issue that was previously mentioned in https://github.com/emacs-evil/evil-collection/issues/63, but it wasn't fixed until now.

Can you consider merging?

Thanks!

### Checklist

Assume you're working on `mpc` mode:

- [x] byte-compiles cleanly
- [x] `M-x checkdoc` is happy. Don't manually write `(provide 'evil-collection-mpc)`, `M-x checkdoc` can do it automatically for you
- [ ] define `evil-collection-mpc-setup` with `defun`
- [ ] define `evil-collection-mpc-mode-maps` with `defconst`
- [ ] All functions should start with `evil-collection-mpc-`

2023-05-25 16:43 UTC, condy0919 requested changes

2023-05-25 16:43 UTC, condy0919 commented on modes/helm/evil-collection-helm.el
> +                    evil-insert-state-cursor '(nil +evil-default-cursor-fn))))))
I suspect `+evil-emacs-cursor-fn` and `+evil-default-cursor-fn` are functions from doom-emacs.

https://github.com/doomemacs/doomemacs/blob/master/modules/editor/evil/config.el#L101-L104

2023-05-30 16:45 UTC, condy0919 commented
```
Eager macro-expansion failure: (wrong-number-of-arguments (2 . 2) 4)
Requiring evil-integration. Set evil-want-integration to t to remove this message.

See https://github.com/emacs-evil/evil-collection/issues/60 for more details.

In toplevel form:
modes/helm/evil-collection-helm.el:69:1:Error: Wrong number of arguments: (2 . 2), 8
make: *** [Makefile:11: compile] Error 1
```

Emacs 26.3 throws an error.

2024-11-23 20:23 UTC, jojojames commented
The change seems inoffensive from what I see but closing for now as there seems to no activity.

2024-11-23 20:23 UTC, closed without merging