Hyrolo
emacs-evil/evil-collection pull request #822
Opened 2024-07-11 14:39 UTC by julian-hoch

### Brief summary of what the package does

hyrolo is part of hyperbole, basically a record manager

### Direct link to the package repository

https://www.gnu.org/software/hyperbole/

### Checklist

I dont know how to check "byte-compiles cleanly", but should be fine ?

Assume you're working on `mpc` mode:

- [? ] byte-compiles cleanly
- [ x] `M-x checkdoc` is happy. Don't manually write `(provide 'evil-collection-mpc)`, `M-x checkdoc` can do it automatically for you
- [x] define `evil-collection-mpc-setup` with `defun`
- [ x] define `evil-collection-mpc-mode-maps` with `defconst`
- [ x] All functions should start with `evil-collection-mpc-`

2024-07-30 16:59 UTC, condy0919 commented
Does hyrole provides `'hyrole` ?

2024-07-31 04:51 UTC, julian-hoch commented
Thanks for the update. 
`M-x byte-compile-file`
runs fine.
And here is the link to hyrolo.el, if that answers your question (it does provide hyrolo).
https://github.com/rswgnu/hyperbole/blob/master/hyrolo.el

2024-08-05 16:02 UTC, condy0919 requested changes

2024-08-05 16:02 UTC, condy0919 commented on modes/hyrolo/evil-collection-hyrolo.el
> +  (evil-collection-define-key 'normal 'hyrolo-mode-map
```elisp
(evil-set-initial-state 'hyrolo-mode 'normal)
```

Explicit setting to normal mode is recommended.

2024-08-08 15:43 UTC, condy0919 commented
> Compiling /home/runner/work/evil-collection/evil-collection/modes/hyrolo/evil-collection-hyrolo.el... the following functions are not known to be defined: hyrolo-to-previous-loc, hyrolo-to-next-loc, hyrolo-outline-show-all, hyrolo-overview

`declare-function` these functions first.

2024-08-12 01:43 UTC, merged